server:
  port: 8003
#  servlet:
#    context-path: /confession
girl:
    cupSize: B
    age: 18
system-params:
    upload: C:/Users/Administrator/Desktop/upload
    uploadplus: C:/Users/Administrator/Desktop/uploadplus
    web-url: http://localhost:8003/confession/
#    web-url: http://123.206.91.106:8003/confession/
    web-url2: localhost:8002